### PR TITLE
Some fixes :)

### PR DESCRIPTION
**Pull request by pierreozoux**
As you can see [here](https://github.com/cozy/cozy-controller/blob/master/server.coffee#L24) the default port is 9002

### CODE REVIEW

**Comment by spiroid** [comment]
@pierreozoux: are you sure about the default port ?
I'm now using the 9104 with nginx as reverse proxy and it works.

Should i also open the 9002 port ?
Any link to a documentation of the plateform components and open ports for each app ?

I also enabled issues on this repository, and i will check the others.

**Comment by pierreozoux** [comment]
Yes here: https://github.com/cozy/cozy-controller/blob/master/server.coffee#L24

I still didn't manage to make it work :/ Do you have the docker compose file with nginx?

**Comment by spiroid** [comment]
Ok, i think i get it now, 

The port number 9104 must be opened, it is the access point of the proxy and thus to all cozy applications : home, etc ...
See : https://github.com/cozy/cozy-proxy/blob/master/server.coffee#L19

The solution, i guess, is to add the 9002 port for direct controller access from outside of the container.

Can you be more specific about what doesn't work ?
Maybe, it will be a better idea to create a new issue, with the output of the `docker-compose logs` command so that other users will benefit from that too :)

Thx

**Comment by spiroid** [comment]
@pierreozoux : i cherry picked your first commit and i updated the dockerfile to add the 9002 port. I also created the #4 issue to add missing documentation and examples.

I'm closing this pull request.
Thx !

**Comment by pierreozoux** [comment]
Ok, I managed to make it working with both ports opened :) Great that you closed!

**Pull request closed without merging**
